name: dv-sports-elt
image: ghcr.io/hasan-tavakoli/dv-sports-etl:staging-20260703003627-5bbab53
service_account: analytics-dev@dv-dev-eu-w1-sports-elt.iam.gserviceaccount.com
region: europe-west1
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
