name: dv-analytics-elt
image: ghcr.io/hasan-tavakoli/dv-sports-etl:main-20260722134410-a4c65cf
service_account: analytics-dev@dv-dev-eu-w1-analytics-elt.iam.gserviceaccount.com
region: europe-west1
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
